"""
Virtual Agent - Simulierte Code-Generierung für Streamlit Cloud
Zeigt realistischen Agent-Workflow ohne echte API-Calls
"""

import time
import random
import streamlit as st
from datetime import datetime

class VirtualAgent:
    """Simuliert einen echten Code-Agenten"""
    
    def __init__(self, name="CodeMaster"):
        self.name = name
        self.steps = []
        self.current_step = 0
        
    def generate_code(self, task_title, task_description, language="python"):
        """Simuliert Code-Generierung Schritt für Schritt"""
        
        # Analyse-Phase
        yield {
            "type": "thought",
            "content": f"Analyzing task: '{task_title}'...",
            "timestamp": datetime.now().strftime("%H:%M:%S")
        }
        time.sleep(0.5)
        
        yield {
            "type": "thought", 
            "content": f"Requirements: {task_description[:50]}...",
            "timestamp": datetime.now().strftime("%H:%M:%S")
        }
        time.sleep(0.3)
        
        # Planung
        yield {
            "type": "action",
            "content": "Creating implementation plan...",
            "timestamp": datetime.now().strftime("%H:%M:%S")
        }
        time.sleep(0.4)
        
        # Code-Generierung basierend auf Task
        if "API" in task_title or "REST" in task_title:
            code = '''from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

app = FastAPI()

class User(BaseModel):
    id: int
    name: str
    email: str

users = []

@app.get("/users")
def get_users():
    return users

@app.post("/users")
def create_user(user: User):
    users.append(user)
    return user

@app.get("/users/{user_id}")
def get_user(user_id: int):
    for user in users:
        if user.id == user_id:
            return user
    raise HTTPException(status_code=404, detail="User not found")
'''
        elif "CSV" in task_title or "data" in task_description.lower():
            code = '''import pandas as pd
import numpy as np

def analyze_csv(filepath):
    """Read and analyze CSV file"""
    df = pd.read_csv(filepath)
    
    stats = {
        "rows": len(df),
        "columns": len(df.columns),
        "numeric_columns": df.select_dtypes(include=[np.number]).columns.tolist(),
        "mean_values": df.mean(numeric_only=True).to_dict(),
        "missing_values": df.isnull().sum().to_dict()
    }
    
    return stats

if __name__ == "__main__":
    result = analyze_csv("data.csv")
    print(result)
'''
        elif "hello" in task_title.lower() or "greet" in task_description.lower():
            code = '''def greet(name: str) -> str:
    """
    Generate a personalized greeting message.
    
    Args:
        name: The name to greet
        
    Returns:
        A greeting string
    """
    return f"Hello, {name}! Welcome to KimiClaw."


def main():
    """Main function"""
    user_name = input("Enter your name: ")
    message = greet(user_name)
    print(message)


if __name__ == "__main__":
    main()
'''
        else:
            code = '''def main():
    """Main function generated by AI"""
    print("Task completed successfully!")
    
    # TODO: Implement specific logic
    return True


if __name__ == "__main__":
    main()
'''
        
        # Zeige Code Zeile für Zeile
        lines = code.split('\n')
        for i, line in enumerate(lines):
            yield {
                "type": "code",
                "content": line,
                "line_number": i + 1,
                "timestamp": datetime.now().strftime("%H:%M:%S")
            }
            time.sleep(0.05)  # Schnelles Tippen
        
        # Review
        yield {
            "type": "thought",
            "content": "Reviewing generated code...",
            "timestamp": datetime.now().strftime("%H:%M:%S")
        }
        time.sleep(0.3)
        
        yield {
            "type": "success",
            "content": f"✓ Code generation complete! {len(lines)} lines written.",
            "timestamp": datetime.now().strftime("%H:%M:%S")
        }
        
        # Wirtschaftssystem
        payment = random.randint(15, 50)
        cost = random.randint(2, 8)
        profit = payment - cost
        
        yield {
            "type": "economy",
            "content": f"💰 Task completed: +${payment} | Cost: -${cost} | Profit: ${profit}",
            "timestamp": datetime.now().strftime("%H:%M:%S"),
            "payment": payment,
            "cost": cost
        }

# Simulierte Task-Ausführung
def simulate_agent_work(task, agent, progress_bar, status_text, output_container):
    """Simuliert die komplette Agent-Arbeit mit UI-Updates"""
    
    virtual_agent = VirtualAgent(agent['name'])
    
    with output_container:
        st.markdown("```")
        
        logs = []
        total_payment = 0
        total_cost = 0
        
        for update in virtual_agent.generate_code(task['title'], task['description']):
            logs.append(update)
            
            # Update UI
            if update['type'] == 'thought':
                st.markdown(f"💭 {update['content']}")
            elif update['type'] == 'action':
                st.markdown(f"⚡ {update['content']}")
            elif update['type'] == 'code':
                if update['line_number'] == 1:
                    st.markdown("📝 Writing code...")
            elif update['type'] == 'success':
                st.markdown(f"✅ {update['content']}")
            elif update['type'] == 'economy':
                st.markdown(f"💰 {update['content']}")
                total_payment = update.get('payment', 0)
                total_cost = update.get('cost', 0)
            
            # Progress
            progress = min(len(logs) / 50, 1.0)
            progress_bar.progress(progress)
            status_text.text(f"Processing... {int(progress * 100)}%")
        
        st.markdown("```")
    
    return total_payment, total_cost

# Schnelle Demo-Ausführung
def quick_demo_task(task_title):
    """Sehr schnelle Demo für Vorschau"""
    responses = {
        "Hello World": '''def greet(name):
    return f"Hello, {name}!"
''',
        "REST API": '''from fastapi import FastAPI
app = FastAPI()

@app.get("/")
def read_root():
    return {"message": "Hello World"}
''',
        "CSV": '''import pandas as pd
df = pd.read_csv("data.csv")
print(df.describe())
'''
    }
    
    for key in responses:
        if key.lower() in task_title.lower():
            return responses[key]
    
    return '''def main():
    print("Task completed!")
'''
